[versions]
version-name = "0.7.0"
version-code = "12"

firebase-appdistribution-gradle = "5.0.0"
firebase-crashlytics-gradle = "3.0.2"
google-services = "4.4.2"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
android-tools = "31.7.2"
# android-tools and agp should be updated together
agp = "8.7.2"
core-ktx = "1.13.1"
coil = "3.0.0-alpha08"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
androidx-tracing = "1.3.0-alpha02"
lifecycle-runtime-ktx = "2.8.6"
activity-compose = "1.9.2"
start-up = "1.2.0"
kotlinx-datetime = "0.6.0"
ktlint = "12.1.1"
secrets = "2.0.1"
desugar = "2.0.4"

detekt = "1.23.6"

# Internal Database
room = "2.6.1"
sqldelight = "2.0.2"
datastore = '1.1.1'
encrypted-prefs = '1.1.0-alpha04'

# Multithreading
kotlinx-coroutines = '1.9.0'

# Network & Serialization
ktor = "2.3.12"
kotlinx-serialization = "1.7.1"

# Depedency Injection
koin = "4.0.0"

# Compose
compose-bom = "2024.10.01"
compose-foundation = "1.7.5"
compose-destinations = "2.1.0-beta09"
material3 = "1.3.1"

compose-shimmer = "1.3.0"

# Timber
timber = "5.0.1"

# Testing
kover = "0.8.3"
screenshot = "0.0.1-alpha07"
androidx-test = "1.6.1"
truth = "1.4.2"
turbine = "1.1.0"

# UI
robolectric = "4.12.2"
androidx-compose-ui-test = "1.7.3"
ui-automator = "2.3.0"

# Mockers
mockito = "5.12.0"
mockito-kotlin = "5.4.0"

[libraries]

android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

# Android X
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "start-up" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidx-tracing" }

kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

# Jetpack Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor", version.ref = "coil" }

# Compose Navigation
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-bottom-sheet = { module = "io.github.raamcosta.compose-destinations:bottom-sheet", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

# Network & Serialization
ktor-client-core = { group = 'io.ktor', name = 'ktor-client-core', version.ref = 'ktor' }
ktor-client-android = { group = 'io.ktor', name = 'ktor-client-android', version.ref = 'ktor' }
ktor-client-logging = { group = 'io.ktor', name = 'ktor-client-logging', version.ref = 'ktor' }
ktor-client-mock = { group = 'io.ktor', name = 'ktor-client-mock', version.ref = 'ktor' }
ktor-client-content-negotiation = { group = 'io.ktor', name = 'ktor-client-content-negotiation', version.ref = 'ktor' }
ktor-serialization-kotlinx-json = { group = 'io.ktor', name = 'ktor-serialization-kotlinx-json', version.ref = 'ktor' }
kotlinx-serialization-json = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-serialization-json', version.ref = 'kotlinx-serialization' }

# Depedency Injection
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-start-up = { group = "io.insert-koin", name = "koin-androidx-startup", version.ref = "koin" }

# Misc
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

youtube-player = 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.1.0'

# Detekt
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Firebase
firebase-bom = 'com.google.firebase:firebase-bom:33.4.0'
firebase-crashlytics = 'com.google.firebase:firebase-crashlytics-ktx:19.2.0'
firebase-analytics = 'com.google.firebase:firebase-analytics-ktx:22.1.2'
firebase-config = 'com.google.firebase:firebase-config-ktx:22.0.0'

# Database
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
encrypted-preferences = { module = "androidx.security:security-crypto-ktx", version.ref = "encrypted-prefs" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }

# Testing

# Core
androidx-test = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# UI
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui-test" }
ui-automator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "ui-automator" }

# Mockers
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gms = { id = "com.google.gms.google-services", version.ref = "google-services" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution-gradle" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }

#detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt-cli" }
#detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt-cli" }

# Plugins defined by this project
divinelink-android-application = { id = "divinelink.android.application", version = "unspecified" }
divinelink-android-application-compose = { id = "divinelink.android.application.compose", version = "unspecified" }
divinelink-android-library = { id = "divinelink.android.library", version = "unspecified" }
divinelink-android-library-compose = { id = "divinelink.android.library.compose", version = "unspecified" }
divinelink-android-feature = { id = "divinelink.android.feature", version = "unspecified" }
divinelink-android-koin = { id = "divinelink.android.koin", version = "unspecified" }
